#!/usr/bin/env bash

function error() {
  echo $@ >&2
}

Dependencies=(  )
for dep in ${Dependencies[@]} ; do
  if [[ -z "$( command -v $dep )" ]] ; then
    if [[ -z "$MissingDeps" ]] ; then
      MissingDeps="$dep"
    else
      MissingDeps="$MissingDeps, $dep"
    fi
  fi
done
if [[ -n "$MissingDeps" ]] ; then
  error "Missing dependencies: $MissingDeps"
  error "Please install them using your distribution's package manager."
  exit 1
fi
